### ISSUE TITLE
Only accept .pm6 for modules in use statements

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/6.d-prep#8]
Here's the proposal: https://github.com/rakudo/rakudo/commit/98e575de00db42101d4879e43fe740a34791c418#commitcomment-27891730

Filing this as a ticket so that it's not forgotten. I think the idea is great.

**Comment by niner** [comment]
How would that work considering that we only know the requested language version when we parse the file in question and we always start out with 6.c semantics?

**Comment by AlexDaniel** [comment]
@niner I think the idea is to remove `pm` here: https://github.com/rakudo/rakudo/blob/98e575de00db42101d4879e43fe740a34791c418/src/core/CompUnit/Repository/FileSystem.pm6#L9-L10

**Comment by niner** [comment]
@AlexDaniel yes, that's how I understood the suggestion and I don't see how that could work in a backwards compatible way.

**Comment by AlexDaniel** [comment]
@niner sorry don't know the details, but can't we make .pm files unusable when you're trying to use them *from* v6.d file (i.e. you don't have to parse the file in question to decide)? I guess it's not as simple as it sounds…

**Comment by Juerd** [comment]
Just a data point: personally I don't use .pm6 or any other digit in file extensions, simply because of the ergonomics involved. The digit row of the keyboard is harder to reach than the alphabetic part, and the middle key, 6, is the worst.

**Comment by lizmat** [comment]
Closing this since this discussion has become pointless now that we have a path forwards with .rakumod and associated extensions after the rename.
