### ISSUE TITLE
Return Failure from failed P6-level .parse 

### ISSUE THREAD

**Issue by raiph** [perl6/6.d-prep#9]
Would there be support for landing [Larry's parse failure patch](https://github.com/rakudo/rakudo/commit/9501edae4f)?

**Comment by AlexDaniel** [comment]
That would be nice. There were [many attempts](https://github.com/rakudo/rakudo/commits/master/src/core/Grammar.pm) to make it work (by keeping the old behavior in v6.c and returning failure in v6.d), but in the end it was reverted [here](https://github.com/rakudo/rakudo/commit/465d91abdfda038cb7feda35f7966be4ec39acf3). We considered struggling through the change also, but it broke too much code out there. I've sent pull requests to many modules in the ecosystem to make them indifferent to the change, but there's nothing we can do about all the scripts out there that rely on that behavior (and judging by the amount of patching in the ecosystem I'm assuming that there are many).

So yes, I'm hoping that someone will have enough tuits to make that change possible.

**Comment by llelf** [comment]
What's needed to make this happen?

**Comment by zoffixznet** [comment]
> What's needed to make this happen?

Most of the 6.d changes are blocked by https://github.com/rakudo/rakudo/issues/1289

**Comment by vrurg** [comment]
Closing via rakudo/rakudo#3103
